name: Deploy function to dev

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: 'coreofscience-dev'
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: info
        run: gcloud info
